In [4]:
import pandas as pd
import os, json

In [2]:
os.path.abspath(os.curdir)

'/home/ai20mtech14009/surbhi/Shadab/Final/Lamol_Nine_Epochs_Without_Adapters'

### Nine Epochs Accuracy

In [18]:
metrics_dir_lll = r"/home/ai20mtech14009/surbhi/Shadab/Final/Lamol_Nine_Epochs_Without_Adapters/models/gpt2/lll/sst_srl_woz.en_0.2/sst"
metrics_dir_finetune = r"/home/ai20mtech14009/surbhi/Shadab/Final/Lamol_Nine_Epochs_Without_Adapters/models/gpt2/finetune/sst_srl_woz.en/sst"

In [19]:
from collections import defaultdict
with open(os.path.join(metrics_dir_lll, "metrics.json")) as file_:
    metrics_json = json.load(file_)
    
task_metrices_dict = defaultdict(list)
for each_metric in metrics_json:
    for each_key, each_val in each_metric.items():
        task_metrices_dict[each_key].append(each_val)

tasks_df = []
column_names = []
for each_metric, result in task_metrices_dict.items():
    tasks_df.append(pd.DataFrame(result))
    fields = [(each_metric,each_key_result) for each_key_result in result[0].keys()]
    column_names.extend(fields)
# last_epoch_metrics = metrics_json[-1]
# last_epoch_metrics["woz.en"]

concatenated_df_normal_nine_epochs = pd.concat(tasks_df, axis=1)

concatenated_df_normal_nine_epochs.columns = pd.MultiIndex.from_tuples(column_names)
concatenated_df_normal_nine_epochs.index = ["Epoch_" + str(each_val) for each_val in range(1,10)]

In [20]:
concatenated_df_normal_nine_epochs

               sst                        srl                woz.en            \
                em        nf1        nem   em       nf1  nem     em  nf1  nem
Epoch_1  85.667216  85.667216  85.667216  0.0  0.077006  0.0    0.0  0.0  0.0
Epoch_2  89.071938  89.071938  89.071938  0.0  0.038799  0.0    0.0  0.0  0.0
Epoch_3  90.170236  90.170236  90.170236  0.0  0.079824  0.0    0.0  0.0  0.0
Epoch_4  90.664470  90.664470  90.664470  0.0  0.024520  0.0    0.0  0.0  0.0
Epoch_5  90.829215  90.829215  90.829215  0.0  0.024520  0.0    0.0  0.0  0.0
Epoch_6  90.993959  90.993959  90.993959  0.0  0.027885  0.0    0.0  0.0  0.0
Epoch_7  90.774300  90.774300  90.774300  0.0  0.024520  0.0    0.0  0.0  0.0
Epoch_8  89.566172  89.566172  89.566172  0.0  0.024520  0.0    0.0  0.0  0.0
Epoch_9  91.103789  91.103789  91.103789  0.0  0.024520  0.0    0.0  0.0  0.0


        joint_goal_em turn_request_em turn_goal_em avg_dialogue
Epoch_1           0.0       32.320778    52.308627    16.160389
Epoch_2           0.0       32.320778    52.308627    16.160389
Epoch_3           0.0       32.320778    52.308627    16.160389
Epoch_4           0.0       32.320778    52.308627    16.160389
Epoch_5           0.0       32.320778    52.308627    16.160389
Epoch_6           0.0       32.320778    52.308627    16.160389
Epoch_7           0.0       32.320778    52.308627    16.160389
Epoch_8           0.0       32.320778    52.308627    16.160389
Epoch_9           0.0       32.320778    52.308627    16.160389

In [124]:
with open(os.path.join(metrics_dir_finetune, "metrics.json")) as file_:
    metrics_json = json.load(file_)
    
task_metrices_dict = defaultdict(list)
for each_metric in metrics_json:
    for each_key, each_val in each_metric.items():
        task_metrices_dict[each_key].append(each_val)

tasks_df = []
column_names = []
for each_metric, result in task_metrices_dict.items():
    tasks_df.append(pd.DataFrame(result))
    fields = [(each_metric,each_key_result) for each_key_result in result[0].keys()]
    column_names.extend(fields)
# last_epoch_metrics = metrics_json[-1]
# last_epoch_metrics["woz.en"]

concatenated_df_finetune_nine_epochs = pd.concat(tasks_df, axis=1)

concatenated_df_finetune_nine_epochs.columns = pd.MultiIndex.from_tuples(column_names)
concatenated_df_finetune_nine_epochs.index = ["Epoch_" + str(each_val) for each_val in range(1,10)]

In [125]:
concatenated_df_finetune_nine_epochs

         sst                      srl                woz.en                 \
          em       nf1       nem   em       nf1  nem     em       nf1  nem
Epoch_1  0.0  0.000000  0.000000  0.0  0.129372  0.0    0.0  0.055750  0.0
Epoch_2  0.0  0.000000  0.000000  0.0  0.114889  0.0    0.0  0.059142  0.0
Epoch_3  0.0  0.109830  0.109830  0.0  0.100182  0.0    0.0  0.032968  0.0
Epoch_4  0.0  0.000000  0.000000  0.0  0.104990  0.0    0.0  0.102904  0.0
Epoch_5  0.0  0.054915  0.054915  0.0  0.112833  0.0    0.0  0.000000  0.0
Epoch_6  0.0  0.000000  0.000000  0.0  0.113644  0.0    0.0  0.028352  0.0
Epoch_7  0.0  0.000000  0.000000  0.0  0.086595  0.0    0.0  0.064732  0.0
Epoch_8  0.0  0.000000  0.000000  0.0  0.153824  0.0    0.0  0.044443  0.0
Epoch_9  0.0  0.054915  0.054915  0.0  0.100632  0.0    0.0  0.037334  0.0


        joint_goal_em turn_request_em turn_goal_em avg_dialogue
Epoch_1           0.0       32.077764    52.308627    16.038882
Epoch_2           0.0       32.077764    52.308627    16.038882
Epoch_3           0.0       32.199271    52.308627    16.099635
Epoch_4           0.0       32.320778    52.308627    16.160389
Epoch_5           0.0       32.199271    52.308627    16.099635
Epoch_6           0.0       32.017011    52.308627    16.008505
Epoch_7           0.0       32.381531    52.308627    16.190765
Epoch_8           0.0       32.199271    52.308627    16.099635
Epoch_9           0.0       32.138518    52.308627    16.069259

In [8]:
metrics_dir_lll = r"./models/gpt2/lll/sst_srl_woz.en_0.2/woz.en"
metrics_dir_finetune = r"./models/gpt2/finetune/sst_srl_woz.en/woz.en"

In [9]:
with open(os.path.join(metrics_dir_lll, "metrics.json")) as file_:
    metrics_json = json.load(file_)

task_metrices_dict = defaultdict(list)
for each_metric in metrics_json:
    for each_key, each_val in each_metric.items():
        task_metrices_dict[each_key].append(each_val)

tasks_df = []
column_names = []
for each_metric, result in task_metrices_dict.items():
    tasks_df.append(pd.DataFrame(result))
    fields = [(each_metric,each_key_result) for each_key_result in result[0].keys()]
    column_names.extend(fields)
# last_epoch_metrics = metrics_json[-1]
# last_epoch_metrics["woz.en"]

concatenated_df_normal_three_epoch = pd.concat(tasks_df, axis=1)

concatenated_df_normal_three_epoch.columns = pd.MultiIndex.from_tuples(column_names)
concatenated_df_normal_three_epoch.index = ["Epoch_" + str(each_val) for each_val in range(1,4)]

In [10]:
concatenated_df_normal_three_epoch

               sst                              srl                        \
                em        nf1        nem         em        nf1        nem
Epoch_1  77.759473  77.759473  77.759473  22.398910  42.414021  26.260791
Epoch_2  82.482153  82.482153  82.482153  24.079964  44.817343  28.441617
Epoch_3  78.143877  78.143877  78.143877  23.761926  44.056944  27.896411

            woz.en                                                      \
                em        nf1        nem joint_goal_em turn_request_em
Epoch_1   8.687728  80.580494  59.416768     31.713244       74.787363
Epoch_2  13.851762  86.449282  71.202916     48.298906       85.236938
Epoch_3  14.580802  87.754371  73.207776     52.673147       86.877278


        turn_goal_em avg_dialogue
Epoch_1    70.899149    53.250304
Epoch_2    77.399757    66.767922
Epoch_3    79.465371    69.775213

In [11]:
with open(os.path.join(metrics_dir_finetune, "metrics.json")) as file_:
    metrics_json = json.load(file_)
    
task_metrices_dict = defaultdict(list)
for each_metric in metrics_json:
    for each_key, each_val in each_metric.items():
        task_metrices_dict[each_key].append(each_val)

tasks_df = []
column_names = []
for each_metric, result in task_metrices_dict.items():
    tasks_df.append(pd.DataFrame(result))
    fields = [(each_metric,each_key_result) for each_key_result in result[0].keys()]
    column_names.extend(fields)
# last_epoch_metrics = metrics_json[-1]
# last_epoch_metrics["woz.en"]

concatenated_df_finetune_three_epoch = pd.concat(tasks_df, axis=1)

concatenated_df_finetune_three_epoch.columns = pd.MultiIndex.from_tuples(column_names)
concatenated_df_finetune_three_epoch.index = ["Epoch_" + str(each_val) for each_val in range(1,4)]

In [12]:
concatenated_df_finetune_three_epoch

         sst                 srl                          woz.en             \
          em  nf1  nem        em        nf1       nem         em        nf1
Epoch_1  0.0  0.0  0.0  4.316220  15.075854  5.633803  12.454435  84.283349
Epoch_2  0.0  0.0  0.0  2.726034  12.638091  3.271240  11.178615  86.861217
Epoch_3  0.0  0.0  0.0  1.953657   8.930820  2.453430  13.547995  87.474037


               nem joint_goal_em turn_request_em turn_goal_em avg_dialogue
Epoch_1  65.431349     42.162819       82.077764    72.904010    62.120292
Epoch_2  69.076549     52.065614       83.961118    75.698663    68.013366
Epoch_3  72.296476     54.556501       86.148238    78.068044    70.352369

In [21]:
concatenated_df_normal_nine_epochs.to_csv("concatenated_df_normal_nine_epochs_adapter_sst.csv")
# concatenated_df_finetune_nine_epochs.to_csv("concatenated_df_finetune_nine_epochs.csv")
# concatenated_df_normal_three_epoch.to_csv("concatenated_df_normal_three_epoch.csv")
# concatenated_df_finetune_three_epoch.to_csv("concatenated_df_finetune_three_epoch.csv")

In [134]:
!pip install --user torchsummary

Requirement already satisfied: torchsummary in /home/ai20mtech14009/anaconda3/envs/LAMOL/lib/python3.7/site-packages (1.5.1)

### Five Epochs New Calculation Without Replay

#### SST

In [5]:
metrics_dir_lll = r"./models/gpt2/lll/sst_srl_woz.en_0.0/sst"
metrics_dir_finetune = r"./models/gpt2/finetune/sst_srl_woz.en/sst"

In [6]:
with open(os.path.join(metrics_dir_lll, "metrics.json")) as file_:
    metrics_json = json.load(file_)

task_metrices_dict = defaultdict(list)
for each_metric in metrics_json:
    for each_key, each_val in each_metric.items():
        task_metrices_dict[each_key].append(each_val)

tasks_df = []
column_names = []
for each_metric, result in task_metrices_dict.items():
    tasks_df.append(pd.DataFrame(result))
    fields = [(each_metric,each_key_result) for each_key_result in result[0].keys()]
    column_names.extend(fields)
# last_epoch_metrics = metrics_json[-1]
# last_epoch_metrics["woz.en"]

concatenated_df_normal_three_epoch_sst = pd.concat(tasks_df, axis=1)

concatenated_df_normal_three_epoch_sst.columns = pd.MultiIndex.from_tuples(column_names)
concatenated_df_normal_three_epoch_sst.index = ["Epoch_" + str(each_val) for each_val in range(1,6)]

NameError: name 'defaultdict' is not defined

In [3]:
concatenated_df_normal_three_epoch_sst

NameError: name 'concatenated_df_normal_three_epoch_sst' is not defined

In [109]:
concatenated_df_normal_three_epoch_sst.to_csv("concatenated_df_ForwardTransfer_withAdapter_Stacking_WithoutReplay_Five_epochs_adapter_sst.csv", index=False)

#### SRL

In [148]:
metrics_dir_lll = r"./models/gpt2/lll/sst_srl_woz.en_0.2/srl"
metrics_dir_finetune = r"./models/gpt2/finetune/sst_srl_woz.en/srl"

with open(os.path.join(metrics_dir_lll, "metrics.json")) as file_:
    metrics_json = json.load(file_)

task_metrices_dict = defaultdict(list)
for each_metric in metrics_json:
    for each_key, each_val in each_metric.items():
        task_metrices_dict[each_key].append(each_val)

tasks_df = []
column_names = []
for each_metric, result in task_metrices_dict.items():
    tasks_df.append(pd.DataFrame(result))
    fields = [(each_metric,each_key_result) for each_key_result in result[0].keys()]
    column_names.extend(fields)
# last_epoch_metrics = metrics_json[-1]
# last_epoch_metrics["woz.en"]

concatenated_df_normal_three_epoch_srl = pd.concat(tasks_df, axis=1)

concatenated_df_normal_three_epoch_srl.columns = pd.MultiIndex.from_tuples(column_names)
concatenated_df_normal_three_epoch_srl.index = ["Epoch_" + str(each_val) for each_val in range(1,6)]

display(concatenated_df_normal_three_epoch_srl)

# concatenated_df_normal_three_epoch.to_csv("concatenated_df_ForwardTransfer_withAdapter_Stacking_WithoutReplay_Five_epochs_adapter_srl.csv", index=False)

               sst                              srl                        \
                em        nf1        nem         em        nf1        nem
Epoch_1  87.699066  87.699066  87.699066  34.984098  57.906229  40.436165
Epoch_2  87.149918  87.149918  87.149918  41.435711  62.733071  46.660609
Epoch_3  89.401428  89.401428  89.401428  43.980009  65.376884  49.477510
Epoch_4  89.566172  89.566172  89.566172  46.796910  67.637288  52.657883
Epoch_5  90.170236  90.170236  90.170236  47.024080  68.020543  52.521581

        woz.en                                                     \
            em        nf1       nem joint_goal_em turn_request_em
Epoch_1    0.0  17.912939  1.215067           0.0       32.320778
Epoch_2    0.0  16.406156  1.640340           0.0       32.320778
Epoch_3    0.0  17.453906  1.275820           0.0       32.320778
Epoch_4    0.0  19.900243  1.822600           0.0       32.320778
Epoch_5    0.0  17.546331  1.336574           0.0       32.320778


        turn_goal_em avg_dialogue
Epoch_1    52.308627    16.160389
Epoch_2    52.308627    16.160389
Epoch_3    52.308627    16.160389
Epoch_4    52.308627    16.160389
Epoch_5    52.308627    16.160389

#### woz

In [149]:
metrics_dir_lll = r"./models/gpt2/lll/sst_srl_woz.en_0.2/woz.en"
metrics_dir_finetune = r"./models/gpt2/finetune/sst_srl_woz.en/woz.en"

with open(os.path.join(metrics_dir_lll, "metrics.json")) as file_:
    metrics_json = json.load(file_)

task_metrices_dict = defaultdict(list)
for each_metric in metrics_json:
    for each_key, each_val in each_metric.items():
        task_metrices_dict[each_key].append(each_val)

tasks_df = []
column_names = []
for each_metric, result in task_metrices_dict.items():
    tasks_df.append(pd.DataFrame(result))
    fields = [(each_metric,each_key_result) for each_key_result in result[0].keys()]
    column_names.extend(fields)
# last_epoch_metrics = metrics_json[-1]
# last_epoch_metrics["woz.en"]

concatenated_df_normal_three_epoch_woz = pd.concat(tasks_df, axis=1)

concatenated_df_normal_three_epoch_woz.columns = pd.MultiIndex.from_tuples(column_names)
concatenated_df_normal_three_epoch_woz.index = ["Epoch_" + str(each_val) for each_val in range(1,6)]

display(concatenated_df_normal_three_epoch_woz)

# concatenated_df_normal_three_epoch.to_csv("concatenated_df_ForwardTransfer_withAdapter_Stacking_WithoutReplay_Five_epochs_adapter_woz.csv", index=False)

               sst                              srl                        \
                em        nf1        nem         em        nf1        nem
Epoch_1  87.589237  87.589237  87.589237  42.889596  63.551911  48.341663
Epoch_2  85.886875  85.886875  85.886875  43.980009  64.453302  50.249886
Epoch_3  89.346513  89.346513  89.346513  45.570195  64.258584  49.795547
Epoch_4  89.511258  89.511258  89.511258  44.979555  65.012903  50.113585
Epoch_5  89.511258  89.511258  89.511258  45.297592  65.494106  50.658791

        woz.en                                                      \
            em        nf1        nem joint_goal_em turn_request_em
Epoch_1    0.0  87.725816  73.936817     53.645200       87.059538
Epoch_2    0.0  90.854399  79.708384     70.473876       88.882139
Epoch_3    0.0  90.527162  79.343864     71.992710       87.910085
Epoch_4    0.0  92.883777  83.110571     78.189550       91.251519
Epoch_5    0.0  93.262394  84.507898     82.685298       90.643985


        turn_goal_em avg_dialogue
Epoch_1    80.801944    70.352369
Epoch_2    85.965978    79.678007
Epoch_3    86.148238    79.951397
Epoch_4    88.213852    84.720535
Epoch_5    90.279465    86.664642

In [64]:
sst_metrics = concatenated_df_normal_three_epoch_sst[[('sst', 'nem'), ('srl', 'nf1'), ('woz.en', 'avg_dialogue')]]
srl_metrics = concatenated_df_normal_three_epoch_srl[[('sst', 'nem'), ('srl', 'nf1'), ('woz.en', 'avg_dialogue')]]
woz_metrics = concatenated_df_normal_three_epoch_woz[[('sst', 'nem'), ('srl', 'nf1'), ('woz.en', 'avg_dialogue')]]

In [65]:
woz_metrics

               sst        srl       woz.en
               nem        nf1 avg_dialogue
Epoch_1  87.589237  63.551911    70.352369
Epoch_2  85.886875  64.453302    79.678007
Epoch_3  89.346513  64.258584    79.951397
Epoch_4  89.511258  65.012903    84.720535
Epoch_5  89.511258  65.494106    86.664642

In [66]:
sst_metrics.columns = sst_metrics.columns.map(lambda x: 'sst_' + '_'.join(x)).str.strip('_')
srl_metrics.columns = srl_metrics.columns.map(lambda x: 'srl_' + '_'.join(x)).str.strip('_')
woz_metrics.columns = woz_metrics.columns.map(lambda x: 'woz_' + '_'.join(x)).str.strip('_')